export const matchData = [
  {
    date: "03.01",
    day: "토",
    time: "14:00",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./JeonBuk.png",
    vsTeam1: "울산",
    vsTeam2: "전북현대",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.02.26 (수)",
    openDate: "12:00 오픈예정",
  },
  {
    date: "03.09",
    day: "일",
    time: "14:00",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./Jeju.png",
    vsTeam1: "울산",
    vsTeam2: "제주",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.04.02 (수)",
    openDate: "12:00 오픈예정",
  },
  {
    date: "04.05",
    day: "토",
    time: "14:00",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./Seoul.png",
    vsTeam1: "울산",
    vsTeam2: "FC서울",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.04.02 (수)",
    openDate: "12:00 오픈예정",
  },
  {
    date: "04.19",
    day: "토",
    time: "14:00",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./Gangwon.png",
    vsTeam1: "울산",
    vsTeam2: "강원",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.02.26 (수)",
    openDate: "12:00 오픈예정",
  },
  {
    date: "05.02",
    day: "금",
    time: "19:30",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./Gwangju.png",
    vsTeam1: "울산",
    vsTeam2: "광주FC",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.04.29 (화)",
    openDate: "12:00 오픈예정",
  },
  {
    date: "05.05",
    day: "월",
    time: "14:00",
    imgSrc1: "./Ulsan.png",
    imgSrc2: "./Pohang.png",
    vsTeam1: "울산",
    vsTeam2: "포항",
    place: "울산 문수 월드컵경기장",
    fullDate: "2025.05.02 (금)",
    openDate: "12:00 오픈예정",
  },
];
